### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by nijel**
Completed and improved Czech translation.

### CODE REVIEW

**Comment by nijel** [comment]
The translation is still a bit clumsy because of the following logic:

https://github.com/MrBartusek/MeteoalarmCard/blob/31f419d37b7e3a8af198b6bf333331b44f57d9b7/src/events-praser.ts#L196-L203

It uses the same event name as a standalone text and as a part of a sentence. Having them separated could result in a much nicer translation.

* Before this PR it is: `Povodeň` / `Žluté povodeň varování`
* This PR workarounds lack of declination as: `Povodeň` / `Žluté varování: povodeň`
* Even better would be: `Povodeň` / `Žluté varování před povodní`

**Comment by MrBartusek** [comment]
@martin131 Can you take a look at that?

**Comment by MrBartusek** [comment]
> The translation is still a bit clumsy because of the following logic:
> 
> https://github.com/MrBartusek/MeteoalarmCard/blob/31f419d37b7e3a8af198b6bf333331b44f57d9b7/src/events-praser.ts#L196-L203
> 
> It uses the same event name as a standalone text and as a part of a sentence. Having them separated could result in a much nicer translation.
> 
> * Before this PR it is: `Povodeň` / `Žluté povodeň varování`
> * This PR workarounds lack of declination as: `Povodeň` / `Žluté varování: povodeň`
> * Even better would be: `Povodeň` / `Žluté varování před povodní`

Quite honestly, I do not speak Czech and I've no idea how to proceed here. I think we can leave this as is for the time being unless anybody would want to provide PR for that.

**Comment by nijel** [comment]
I think what this PR is good enough, it's just a note that the code could be improved to better support localization.

**Review by MrBartusek — APPROVED** [review]

**Comment by MrBartusek** [comment]
Thank you!

**Pull request merged**
