### PR TITLE
Integrations rework & MeteoFrance integration

### PR DESCRIPTION
**Pull request by Nsbx**
Hello 😄

I found your project and thought it was really cool. The only problem was with MeteoAlarm, i tried multiple time but impossible to make it works. I also tried with the custom integration MeteoAlarmeu same problem.
So i made some modification to make your card works with the official integration "MeteoFrance" (https://www.home-assistant.io/integrations/meteo_france/).

I made some refactoring to use the design pattern "strategy"

So the code can be easily extended to much other integration.

I also fixed typo and fix the code style (auto indent from vscode)

I'm French native, and i work mostly with PHP so i'm sorry for my bad english and probably my bad JS :')

If you have question or you want i do some modification don't hesitate.

Edit: I forget, i have transformed the code for meteoalarm & meteoalarmeu into "strategy" but because neither of them works on my instance i don't know if this work.

### CODE REVIEW

**Comment by Nsbx** [comment]
Hm i see the build error i fix that

**Comment by MrBartusek** [comment]
@Nsbx Hey, thanks for contributing! Build failed because you made a lot of code style changes that don't match eslint, I'm sure that most of them can be auto-fixed by it

**Comment by Nsbx** [comment]
Sorry for all code style change, i never use eslint before, i hope i fixed all my mistakes.
I also edited the readme to understand how the new "system" works.
I made this design pattern change because unfortunately the entity who "report" weather events is not binary sensor like meteoalarm.
But i thinks this is better like this, the whole system can be extended without touch to the core system

**Review by MrBartusek — COMMENTED** [review]
Hey, I', glad that you had refactored that code! There are a couple of things that I don't like the thought

I don't think that user needs to select the type of their integration. There can easily be an `automatic` mode where strategy will be chosen based on the attributes of the sensor, `supports()` can be changed to do that for example. It still would be a good idea to give user ability to overwrite the automated system thought

I don't think that `isAvaiable()` should be written in every integration, i don't know any sensor that reports that they are unavailable other than setting their state to `unavailable`

I really don't like the `Strategy` name.  It will be much better if these classes were to be named `MeteoAlarmIntegration` `MeteoFranceIntegration` etc.

I am not sure if that's needed to separate these integrations intro `integrations` and `custom_integrations` i bet there won't be more than 10 integrations anyway so it just complicates file structure.

**Comment by Nsbx** [comment]
Thank for your advices, i changed my code in consequence.
Also i discovered a problem, how do you manage multi-events ?
Currenlty in my city in France there is a wind and thunderstorm alert, but with my actual code only one of these event while be displayed.

**Comment by MrBartusek** [comment]
@Nsbx Well, the way that the card is made doesn't allow for displaying more than one event so it should display the one with higher severity and if there are a couple with the same severity, the more important one. For example, it's normal that if there is a thunderstorm there is also wind so a thunderstorm alert is more important.

**Comment by Nsbx** [comment]
@MrBartusek 
I had thought about it but I wasn't sure, thank for your clarification.
I kept the same order of events of your class so i think this should works.

**Comment by MrBartusek** [comment]
@Nsbx I've made some changes, 

- Meteoalarm and Meteoalarm weren't working, they are fixed now
- Automatic now works a little bit differently, user can select integration type or do it automatically
- Some general code clarity improvements

I think this PR is ready to be merged, just let me know are you OK with these changes

**Review by MrBartusek — APPROVED** [review]

**Comment by Nsbx** [comment]
Thank you for your fix, i tried to not break the original code but without testing this is impossible.
If is ok for you let's go :D

**Pull request merged**
