### PR TITLE
Add missing events to MeteoFrance & update French translation

### PR DESCRIPTION
**Pull request by Nsbx**
Hey :)

I finally take a look into the source code to find the complete list of event, instead find them one by one ...
I don't know why I didn't do that directly

Also, I found some invisible char into translation, I replace them by space like other translation.

Fixes: #74

### CODE REVIEW

**Review by MrBartusek — APPROVED** [review]

**Comment by MrBartusek** [comment]
Thanks!

**Comment by Lynilia** [comment]
> Also, I found some invisible char into translation, I replace them by space like other translation.

Hello,

Those characters were non-breaking spaces ("espace insécable" in French), they look like normal spaces but are used to prevent line breaks from throwing punctuation alone on a new line.

More info on Wikipedia: [en](https://en.wikipedia.org/wiki/Non-breaking_space) - [fr](https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable)

**Comment by MrBartusek** [comment]
@Lynilia there shouldn't be any multi-line text on the card. If this is a case, it's a bug.

**Comment by Nsbx** [comment]
Oh sorry about that @Lynilia, i know what is an insecable space, but my IDE just said "invisible character".
I think the best practice about that is to use HTML entities (&nbsp; &#160; or &#xA0;) like this we know where special symbol are and which symbol are used

**Comment by MrBartusek** [comment]
@Lynilia I actually forgot about this, thanks!

@Nsbx to be honest it seams like this is French specific thing so you can go ahead and change it to non-breaking spaces in the translation file

**Pull request merged**
