### PR TITLE
Add Slovak translation

### PR DESCRIPTION
**Pull request by Marlo461**

### CODE REVIEW

**Comment by Marlo461** [comment]
I don't know if it's good anymore? If something is wrong see what and how I can fix it.

**Review by MrBartusek — CHANGES_REQUESTED** [review]
Update the translation file to `sk` from `sk.json`

**Comment by Marlo461** [comment]
Fixed  ;)

**Review by MrBartusek — APPROVED** [review]

**Comment by MrBartusek** [comment]
Thanks!

**Comment by Marlo461** [comment]
I was happy to help

**Comment by Marlo461** [comment]
Hi, I have one question, how do I change the language on the card?  I entered these parameters but the language is still in English

  - type: custom:meteoalarm-card
    entity: binary_sensor.meteoalarm
    override_headline: false
    hide_when_no_warning: false
    integration: meteoalarm
    language: sk

**Comment by MrBartusek** [comment]
> Hi, I have one question, how do I change the language on the card? I entered these parameters but the language is still in English
> 
> * type: custom:meteoalarm-card
>   entity: binary_sensor.meteoalarm
>   override_headline: false
>   hide_when_no_warning: false
>   integration: meteoalarm
>   language: sk

You need to wait for new release or update to `master` version

image

**Pull request merged**
