### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by ajtudela**
I added spanish translations to localization folder.

Keep doing such a great work!

### CODE REVIEW

**Review by MrBartusek — CHANGES_REQUESTED** [review]
Hey, thanks for contributing! Everything is great but you forgot to add language to README

**Comment by ajtudela** [comment]
My bad. Close this one and I'll make a new pull request with the Readme

**Comment by MrBartusek** [comment]
> My bad. Close this one and I'll make a new pull request with the Readme

You can actually push more commits to master on your fork and they will appear in this PR

**Comment by ajtudela** [comment]
I didn't know. Done!

**Review by MrBartusek — APPROVED** [review]

**Pull request merged**
