### PR TITLE
Tweak Dutch translation

### PR DESCRIPTION
**Pull request by BartEngelen**

### CODE REVIEW

**Review by MrBartusek — CHANGES_REQUESTED** [review]
Update to upstream master and resolve merge conflicts

**Comment by BartEngelen** [comment]
> Update to upstream master and resolve merge conflicts

Hello,
Can you help me with that ?
How can I do that ?
I only want to replace some value's in nl.json file
Greetings,
Bart

**Comment by MrBartusek** [comment]
@BartEngelen Yep no problem, I can help you with that!

You are doing a couple of mistakes:
- You shouldn't work on `master` branch instead you should create branches for specific pull requests like `tweak-dutch`
- Your all branches should be up to date

Navigate to your repo and use these commands **WARNING: THAT WILL DELETE YOU CURRENT CHANGES**:
```
git fetch upstream
git checkout master
git reset --hard upstream/master
```
That will sync `master` branches
Then create a separate branch  `tweak-dutch` do changes on it and then make a PR from it

To have fewer problems in the future before doing anything click that button on your fork

image

and then do `git fetch` and create branch from it. It will make sure that you are working on the newest code

**Comment by BartEngelen** [comment]
> @BartEngelen Yep no problem, I can help you with that!
> 
> You are doing a couple of mistakes:
> 
> * You shouldn't work on `master` branch instead you should create branches for specific pull requests like `tweak-dutch`
> * Your all branches should be up to date
> 
> Navigate to your repo and use these commands **WARNING: THAT WILL DELETE YOU CURRENT CHANGES**:
> 
> ```
> git fetch upstream
> git checkout master
> git reset --hard upstream/master
> ```
> 
> That will sync `master` branches
> Then create a separate branch `tweak-dutch` do changes on it and then make a PR from it
> 
> To have fewer problems in the future before doing anything click that button on your fork
> 
> image
> 
> and then do `git fetch` and create branch from it. It will make sure that you are working on the newest code

**Pull request closed without merging**
