### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by Jugom**
add few missing translations to Spanish localization

### CODE REVIEW

**Comment by MrBartusek** [comment]
@ajtudela

**Comment by ajtudela** [comment]
@Jugom I made a few reviews. In this case "Escalado" instead of "Escala" is a better translation ;)

**Comment by Jugom** [comment]
> @Jugom I made a few reviews. In this case "Escalado" instead of "Escala" is a better translation ;)

I was myself between the two, so sure thing. o7

**Comment by ajtudela** [comment]
> > @Jugom I made a few reviews. In this case "Escalado" instead of "Escala" is a better translation ;)
> 
> I was myself between the two, so sure thing. o7

Great, push a new commit with the fixes, so we can merge it.

**Comment by Jugom** [comment]
> > > @Jugom I made a few reviews. In this case "Escalado" instead of "Escala" is a better translation ;)
> > 
> > 
> > I was myself between the two, so sure thing. o7
> 
> Great, push a new commit with the fixes, so we can merge it.

sorry about that. busy off the grid weekend. I have submitted the changes.
cheers

**Review by MrBartusek — APPROVED** [review]
LGTM, Thank You!

**Pull request merged**
